language: python
sudo: false
python:
- '3.5'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- pip install -r requirements.txt
- wget -q https://github.com/Cruel/3dstex/releases/download/1.1/3dstex-linux-x64
- wget -q $TITLEKEYSURL -O encTitleKeys.bin
- wget -q $PREVCACHEURL -O cache.tar.gz
- echo -e $CTRCERT > ctr-common-1.crt
- echo -e $CTRKEY > ctr-common-1.key
- chmod +x 3dstex-linux-x64
- mkdir -p cache
- tar -xaf cache.tar.gz -C cache

script:
- ./gen_cache.py -i cache
- ./3dstex-linux-x64 -bro etc1 images/*.png

before_deploy:
- export RELEASE_FILENAME=cache-$TRAVIS_TAG
- tar -czf $RELEASE_FILENAME-jpg.tar.gz data.json images/*.jpg
- tar -czf $RELEASE_FILENAME-png.tar.gz data.json images/*.png
- tar -czf $RELEASE_FILENAME-etc1.tar.gz data.json images/*.bin

branches:
  only:
    - /^r.*/

deploy:
  provider: releases
  api_key:
    secure: VVDCmX11YK/WLZg7ieoTxm374ZPyzA9fJn1u6uhdGqlZ3s19YN4B8FP65AE7tU0cKYF17NBERyvdVQ3vvluOjlUSwOH7MbX3SZ9PlEqfOUgiYT9cw2oNYV3qhLECS6YAcaOLYSOZzFZ6bU+LHvz3mqK48LSlNP9HEJES4tnDSiENq6gDT50eLK9ae3C1Pk6SpyfCthGDCZqEiJggp+KsvqRV2mIKDOF0r6/84ggGJZggpS+Xb1tP4k70DqRhN4bxuR5YbEYtvGHo8OFSYqLh53tjfxCasB7BjUiRHkY+eALXMiM2fFL7RRbTNOyIA6clk/HjaGwSeCni3R9Y0RD7xbLvnz0Y/8I6ywn8bZOIrMY82s/XNa33qUcXAIUiGRJeYTIem0hayAxGjDZY4/WtL11hdMvW/dotLdYXpBLLX0yCdy2LjpYbTD2CNr2czWhSiXJPoKrVJd/Vk9i1udnvE9HKCaWF0u8MA4z3dTR0CeWwnabEIVoSpiBvNQWP5QhX2WQU1s3Rfs+0+Dmp52H2HGotvBf8xqsyOR2YQ3lR570FDLuorC5PPpxnx5pC6qZGNCir8/tBe5NQs98xjjfDzhqCp519UGiNol+tIosqaiFFerrlLeSOqIgDjfj4TEBzJcLHKHOXRLVmaTaL7bJUwxzQleWIFD8qIhJpnqHkMIQ=
  file:
    - $RELEASE_FILENAME-jpg.tar.gz
    - $RELEASE_FILENAME-png.tar.gz
    - $RELEASE_FILENAME-etc1.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: Cartman123/shop-cache
